# -*- coding: utf-8 -*-
"""Suresh_FirstProject_Nest4.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1Si6xjzbOGu7VLhBX5m2CleuOWVYUINL7

# **Assignment No.1**
"""

print("First Assignment of Nest4Code")

"""# Problem No.1

QN: Swap Three Variables without temporary variables
"""

a=1
b=2
c=5
a,b,c=b,c,a

print("a "+str(a))
print("b "+str(b))
print("c "+str(c))

"""#Problem No.2"""

QN: To calculate area of the room

length=float(input("Enter length of the Room:"))
width=float(input("Enter width of the Room:"))
area= length *width
print("Area of the Room " +str(area))

length=float(input("Enter length of the Room:"))
width=float(input("Enter width of the Room:"))
area= length *width
print("Area of the Room " +str(round(area, 2)))

length=float(input("Enter length of the Room:"))
width=float(input("Enter width of the Room:"))
area= length *width
print("Area of the Room " +str(round(area, 2)))

length=float(input("Enter length of the Room:"))
width=float(input("Enter width of the Room:"))
area= length *width
print("Area of the Room " +str(round(area, 2)))

"""#PROBLEM No.3"""

Sum of first positive 'N' Integers

n=int(input("enter a number: "))
sum_first_n = n*(n+1)/2
print("Sum "+str(sum_first_n))

n=int(input("enter a number: "))
sum_first_n = n*(n+1)/2
print("Sum "+str(sum_first_n))

n=int(input("enter a number: "))
sum_first_n = n*(n+1)/2
print("Sum "+str(sum_first_n))

n=int(input("enter a number: "))
sum_first_n = int(n*(n+1)/2)
print("Sum "+str(sum_first_n))